DOMAIN = "daily_artwork"
PLATFORMS = ["sensor"]
SENSOR_NAME = "每日名画2"
SENSOR_ICON = "mdi:palette"

NEW_SENSOR_NAME = "每日名画1"
NEW_SENSOR_ICON = "mdi:image"

QUOTE_SENSOR_NAME = "每日一言"
QUOTE_SENSOR_ICON = "mdi:furigana-vertical"
RESOURCE_URL_TEMPLATE_QUOTE = "https://api.codelife.cc/yiyan/info?lang=cn"
QUOTE_API_SIGNATURE_KEY = "your_signature_key_here"
QUOTE_API_ORIGIN = "https://codelife.cc"
LOGIN_URL = "https://arrrt.wedea.cn/api/api/notcheck/autoLogin?languageId=1"
RESOURCE_URL_TEMPLATE_OLD = "https://api.getdailyart.com/api/artworks/daily"
RESOURCE_URL_TEMPLATE_NEW = "https://arrrt.wedea.cn/api/api/notcheck?languageId=1&date={}&searchType=2"
CDN_PREFIX = "https://arrrt.oss-cn-hangzhou.aliyuncs.com/"
THUMB_SUFFIX = "_thumb.jpg"

# 电影相关常量
MOVIE_SENSOR_NAME = "每日电影"
MOVIE_SENSOR_ICON = "mdi:movie"
RESOURCE_URL_MOVIE = "https://api.codelife.cc/itab/todayMovie?lang=cn&version=v2"
USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51"
SIGNATURE_KEY = "your_signature_key_here"
ORIGIN = "https://codelife.cc"
SEC_FETCH_MODE = "cors"
SEC_FETCH_SITE = "cross-site"

# 电影数据属性映射
ATTR_MOV_TITLE = "mov_title"
ATTR_MOV_AREA = "mov_area"
ATTR_MOV_DIRECTOR = "mov_director"
ATTR_MOV_YEAR = "mov_year"
ATTR_MOV_TYPE = "mov_type"
ATTR_MOV_RATING = "mov_rating"
ATTR_MOV_INTRO = "mov_intro"
ATTR_MOV_TEXT = "mov_text"
ATTR_MOV_PIC = "mov_pic"
ATTR_POSTER_URL = "poster_url"
ATTR_MOV_LINK = "mov_link"
ATTR_DATE = "date"
ATTR_BG_COLOR = "bgColor"
ATTR_COLOR = "color"